### ISSUE TITLE
win 10 2016 ltbs 32 bit error

### ISSUE THREAD

**Issue by youngcheater** [srounet/Pymem#46]
1. my python version is 3.9.1
2. os version 32 bit 
3. pymem version 1.7

**Expected behavior**
I am getting this error when i am trying to run my program.

**Traceback**
C:\Users\odbie\Desktop\python>python main.py
2021-02-07 21:01:28,160 - pymem - DEBUG - Process 7780 is being debugged
Traceback (most recent call last):
  File "C:\Users\odbie\Desktop\python\main.py", line 1, in <module>
    from Libary import *
  File "C:\Users\odbie\Desktop\python\Libary.py", line 11, in <module>
    pm = pymem.Pymem("Vidgar.exe")
  File "C:\Program Files\Python39-32\lib\site-packages\pymem\__init__.py", line 47, in __init__
    self.check_wow64()
  File "C:\Program Files\Python39-32\lib\site-packages\pymem\__init__.py", line 52, in check_wow64
    verdict = pymem.process.is_64_bit(self.process_handle)
  File "C:\Program Files\Python39-32\lib\site-packages\pymem\process.py", line 357, in is_64_bit
    response = pymem.ressources.kernel32.IsWow64Process(handle, ctypes.byref(Wow64Process))
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert

**Additional context**

**Comment by srounet** [comment]
It's not the first time I'm seeing this and I would like to know how to reproduce it so I can manage to debug it and fix the issue.
If you could provide a reproducible environment I could have a look and try to fix the issue.

**Comment by srounet** [comment]
Could you try with this commit: https://github.com/srounet/Pymem/commit/1d1b1095c097333941c01ef96125dd6f3b7f22a7

**Comment by StarrFox** [comment]
this issue should be fixed by the mentioned commit
